#!/usr/bin/env python
import sys
import os
import argparse
from repoman_client.__version__ import version
from repoman_client.parsers import RepomanCLI
from repoman_client import subcommands
from repoman_client.config import config


def main():

    # The main dispatcher.
    main_parser = RepomanCLI(version=version)

    # Subcommands are added in the order that help will be generated.
    # Subcommand groups are automatically created based on the 'command_group'
    # class attribute for each subcommand.  If 'command_group' is None, the
    # subcommand will be added to a generic group called 'subcommands'
    main_parser.add_command(subcommands.config.MakeConfig)
    main_parser.add_command(subcommands.up_down.Get)
    main_parser.add_command(subcommands.up_down.Save)
    main_parser.add_command(subcommands.modify.Rename)
    main_parser.add_command(subcommands.remove.Delete)
    main_parser.add_command(subcommands.listing.List)

    main_parser.add_command(subcommands.listing.ListUsers)
    main_parser.add_command(subcommands.listing.ListGroups)
    main_parser.add_command(subcommands.listing.ListImages)

    main_parser.add_command(subcommands.describe.DescribeUser)
    main_parser.add_command(subcommands.describe.DescribeGroup)
    main_parser.add_command(subcommands.describe.DescribeImage)

    main_parser.add_command(subcommands.create.CreateUser)
    main_parser.add_command(subcommands.create.CreateGroup)
    main_parser.add_command(subcommands.create.CreateImage)

    main_parser.add_command(subcommands.modify.ModifyUser)
    main_parser.add_command(subcommands.modify.ModifyGroup)
    main_parser.add_command(subcommands.modify.ModifyImage)

    main_parser.add_command(subcommands.remove.RemoveUser)
    main_parser.add_command(subcommands.remove.RemoveGroup)
    main_parser.add_command(subcommands.remove.RemoveImage)

    main_parser.add_command(subcommands.sharing.ShareImage)
    main_parser.add_command(subcommands.sharing.UnshareImage)

    main_parser.add_command(subcommands.group_membership.AddUser)
    main_parser.add_command(subcommands.group_membership.RemoveUser)

    main_parser.add_command(subcommands.permissions.AddPermission)
    main_parser.add_command(subcommands.permissions.RemovePermission)

    main_parser.add_command(subcommands.snapshot.SnapshotSystem)
    main_parser.add_command(subcommands.up_down.UploadImage)
    main_parser.add_command(subcommands.up_down.DownloadImage)

    main_parser.add_command(subcommands.diagnostic.Whoami)
    main_parser.add_command(subcommands.diagnostic.About)

    # Execute Main Parser
    main_parser()


if __name__ == '__main__':
    main()

