#!/usr/bin/env python
import sys
import argparse
from repoman_client.parsers import repoman_cli
from repoman_client.subcommands.help import Help
from repoman_client.subcommands.version import Version
from repoman_client.subcommands.config import MakeConfig

# Add all subcommands here:
repoman_cli.add_subcommand(Help())
repoman_cli.add_subcommand(Version())
repoman_cli.add_subcommand(MakeConfig())

# Ask the parser and subparsers to parse the command line arguments.
args = repoman_cli.get_arg_parser().parse_args()

# Run the subcommand function
args.func(args)

# We're done!
sys.exit(0)

# If we decide to go with this OO approach, the rest of this file will have to
# be moved to individual subcommand classes.  See MakeConfig and Help for
# examples.





# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
#                             Image Manipulation Subcommands                          #
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Subcommand: create-image
p_create_image = sp.add_parser('create-image', add_help=False)
p_create_image.add_argument('image') 
p_create_image.add_argument('-o', '--owner')
p_create_image.add_argument('-f', '--file')
p_create_image.add_argument('-d', '--description')
p_create_image.add_argument('--os_variant')
p_create_image.add_argument('--os_arch')
p_create_image.add_argument('--os_type')
p_create_image.add_argument('--hypervisor')
p_create_image.add_argument('-a', '--unauthenticated_access', choices=['True', 'False'])
#p_create_image.set_defaults(func=ci)

p_ci = sp.add_parser('ci', add_help=False, parents=[p_create_image])
#p_ci.set_defaults(func=ci)

# Subcommand: describe-image
p_describe_image = sp.add_parser('describe-image', add_help=False)
p_describe_image.add_argument('image') 
p_describe_image.add_argument('-o', '--owner')
#p_describe_image.set_defaults(func=di)

p_di = sp.add_parser('di', add_help=False, parents=[p_describe_image])
#p_di.set_defaults(func=di)

# Subcommand: get-image
p_get_image = sp.add_parser('get-image', add_help=False)
p_get_image.add_argument('image') 
p_get_image.add_argument('-o', '--owner')
p_get_image.add_argument('-p', '--path')
#p_get_image.set_defaults(func=gi)

p_gi = sp.add_parser('gi', add_help=False, parents=[p_get_image])
#p_gi.set_defaults(func=gi)

# Subcommand: list-images
p_list_images = sp.add_parser('list-images', add_help=False)
p_list_images.add_argument('-o', '--owner')
p_list_images.add_argument('-g', '--group')
p_list_images.add_argument('-a', '--all', action='store_const', const='yes')
p_list_images.add_argument('-l', '--long', action='store_const', const='yes')
p_list_images.add_argument('-U', '--url', action='store_const', const='yes')
p_list_images.add_argument('-s', '--shared_with', nargs=2)
#p_list_images.set_defaults(func=li)

p_li = sp.add_parser('li', add_help=False, parents=[p_list_images])
#p_li.set_defaults(func=li)

# Subcommand: modify-image
p_modify_image = sp.add_parser('modify-image', add_help=False)
p_modify_image.add_argument('image') 
p_modify_image.add_argument('-o', '--owner')
p_modify_image.add_argument('-d', '--description')
p_modify_image.add_argument('--os_variant')
p_modify_image.add_argument('--os_arch')
p_modify_image.add_argument('--os_type')
p_modify_image.add_argument('--hypervisor')
p_modify_image.add_argument('-u', '--unauthenticated_access', choices=['True', 'False'])
p_modify_image.add_argument('-n', '--new_name')
#p_modify_image.set_defaults(func=mi)

p_mi = sp.add_parser('mi', add_help=False, parents=[p_modify_image])
#p_mi.set_defaults(func=mi)

# Subcommand: put-image
p_put_image = sp.add_parser('put-image', add_help=False)
p_put_image.add_argument('file')
p_put_image.add_argument('image')
p_put_image.add_argument('-o', '--owner')
#p_put_image.set_defaults(func=pi)

p_pi = sp.add_parser('pi', add_help=False, parents=[p_put_image])
#p_pi.set_defaults(func=pi)

# Subcommand: remove-image
p_remove_image = sp.add_parser('remove-image', add_help=False)
p_remove_image.add_argument('image')
p_remove_image.add_argument('-o', '--owner')
p_remove_image.add_argument('-f', '--force', action='store_const', const='yes')
#p_remove_image.set_defaults(func=ri)

p_ri = sp.add_parser('ri', add_help=False, parents=[p_remove_image])
#p_ri.set_defaults(func=ri)

# Subcommand: save-image
p_save_image = sp.add_parser('save-image', add_help=False)
p_save_image.add_argument('image')
p_save_image.add_argument('-o', '--owner')
p_save_image.add_argument('-f', '--force', action='store_const', const='yes')
p_save_image.add_argument('--gzip', action='store_const', const='yes')
p_save_image.add_argument('--resize', type=int)
p_save_image.add_argument('--verbose', action='store_const', const='yes')
p_save_image.add_argument('--clean', action='store_const', const='yes')
p_save_image.add_argument('-d', '--description')
p_save_image.add_argument('--os_variant')
p_save_image.add_argument('--os_arch')
p_save_image.add_argument('--os_type')
p_save_image.add_argument('--hypervisor')
p_save_image.add_argument('-u', '--unauthenticated_access', choices=['True', 'False'])
#p_save_image.set_defaults(func=si)

p_si = sp.add_parser('si', add_help=False, parents=[p_save_image])
#p_si.set_defaults(func=si)

# Subcommand: share-image-with-groups
p_share_image_with_groups = sp.add_parser('share-image-with-groups', add_help=False)
p_share_image_with_groups.add_argument('image')
p_share_image_with_groups.add_argument('-o', '--owner')
p_share_image_with_groups.add_argument('groups', nargs='+')
#p_share_image.set_defaults(func=sig)

p_sig = sp.add_parser('sig', add_help=False, parents=[p_share_image_with_groups])
#p_sig.set_defaults(func=sig)

# Subcommand: share-image-with-users
p_share_image_with_users = sp.add_parser('share-image-with-users', add_help=False)
p_share_image_with_users.add_argument('image')
p_share_image_with_users.add_argument('-o', '--owner')
p_share_image_with_users.add_argument('users', nargs='+')
#p_share_image.set_defaults(func=siu)

p_siu = sp.add_parser('siu', add_help=False, parents=[p_share_image_with_users])
#p_siu.set_defaults(func=siu)

# Subcommand: unshare-image-from-groups
p_unshare_image_from_groups = sp.add_parser('unshare-image-from-groups', add_help=False)
p_unshare_image_from_groups.add_argument('image')
p_unshare_image_from_groups.add_argument('-o', '--owner')
p_unshare_image_from_groups.add_argument('groups', nargs='+')
#p_unshare_image.set_defaults(func=uig)

p_uig = sp.add_parser('uig', add_help=False, parents=[p_unshare_image_from_groups])
#p_uig.set_defaults(func=uig)

# Subcommand: unshare-image-from-users
p_unshare_image_from_users = sp.add_parser('unshare-image-from-users', add_help=False)
p_unshare_image_from_users.add_argument('image')
p_unshare_image_from_users.add_argument('-o', '--owner')
p_unshare_image_from_users.add_argument('users', nargs='+')
#p_unshare_image.set_defaults(func=uiu)

p_uiu = sp.add_parser('uiu', add_help=False, parents=[p_unshare_image_from_users])
#p_uiu.set_defaults(func=uiu)

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
#                             User Manipulation Subcommands                           #
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Subcommand: create-user
p_create_user = sp.add_parser('create-user', add_help=False)
p_create_user.add_argument('user')
p_create_user.add_argument('client_dn')
p_create_user.add_argument('-f', '--full_name')
p_create_user.add_argument('-e', '--email')
#p_create_user.set_defaults(func=cu)

p_cu = sp.add_parser('cu', add_help=False, parents=[p_create_user])
#p_cu.set_defaults(func=cu)

# Subcommand: describe-user
p_describe_user = sp.add_parser('describe-user', add_help=False)
p_describe_user.add_argument('user')
#p_describe_user.set_defaults(func=du)

p_du = sp.add_parser('du', add_help=False, parents=[p_describe_user])
#p_du.set_defaults(func=du)

# Subcommand: list-users
p_list_users = sp.add_parser('list-users', add_help=False)
p_list_users.add_argument('-l', '--long', action='store_const', const='yes')
p_list_users.add_argument('-g', '--group')
#p_list_users.set_defaults(func=lu)

p_lu = sp.add_parser('lu', add_help=False, parents=[p_list_users])
#p_lu.set_defaults(func=lu)

# Subcommand: modify-user
p_modify_user = sp.add_parser('modify-user', add_help=False)
p_modify_user.add_argument('user')
p_modify_user.add_argument('client_dn')
p_modify_user.add_argument('-f', '--full_name')
p_modify_user.add_argument('-e', '--email')
p_modify_user.add_argument('-n', '--new_name')
#p_modify_user.set_defaults(func=mu)

p_mu = sp.add_parser('mu', add_help=False, parents=[p_modify_user])
#p_mu.set_defaults(func=mu)

# Subcommand: remove-user
p_remove_user = sp.add_parser('remove-user', add_help=False)
p_remove_user.add_argument('user')
p_remove_user.add_argument('-f', '--force', action='store_const', const='yes')
#p_remove_user.set_defaults(func=ru)

p_ru = sp.add_parser('ru', add_help=False, parents=[p_remove_user])
#p_ru.set_defaults(func=ru)

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
#                             Group Manipulation Subcommands                          #
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Subcommand: add-permissions-to-group
p_add_permissions_to_group = sp.add_parser('add-permissions-to-group', add_help=False)
p_add_permissions_to_group.add_argument('group')
p_add_permissions_to_group.add_argument('permissions', nargs='+')
#p_add_permissions_to_group.set_defaults(func=apg)

p_apg = sp.add_parser('apg', add_help=False, parents=[p_add_permissions_to_group])
#p_apg.set_defaults(func=apg)

# Subcommand: add-users-to-group
p_add_users_to_group = sp.add_parser('add-users-to-group', add_help=False)
p_add_users_to_group.add_argument('group')
p_add_users_to_group.add_argument('users', nargs='+')
#p_add_users_to_group.set_defaults(func=aug)

p_aug = sp.add_parser('aug', add_help=False, parents=[p_add_users_to_group])
#p_aug.set_defaults(func=aug)

# Subcommand: create-group
p_create_group = sp.add_parser('create-group', add_help=False)
p_create_group.add_argument('group')
p_create_group.add_argument('-u', '--users', nargs='+')
p_create_group.add_argument('-p', '--permissions', nargs='+')
#p_create_group.set_defaults(func=cg)

p_cg = sp.add_parser('cg', add_help=False, parents=[p_create_group])
#p_cg.set_defaults(func=cg)

# Subcommand: describe-group
p_describe_group = sp.add_parser('describe-group', add_help=False)
p_describe_group.add_argument('group')
#p_describe_group.set_defaults(func=dg)

p_dg = sp.add_parser('dg', add_help=False, parents=[p_describe_group])
#p_dg.set_defaults(func=dg)

# Subcommand: list-groups
p_list_groups = sp.add_parser('list-groups', add_help=False)
p_list_groups.add_argument('-l', '--long', action='store_const', const='yes')
p_list_groups.add_argument('-a', '--all', action='store_const', const='yes')
p_list_groups.add_argument('-u', '--user')
#p_list_groups.set_defaults(func=lg)

p_lg = sp.add_parser('lg', add_help=False, parents=[p_list_groups])
#p_lg.set_defaults(func=lg)

# Subcommand: modify-group
p_modify_group = sp.add_parser('modify-group', add_help=False)
p_modify_group.add_argument('group')
p_modify_group.add_argument('-u', '--users', nargs='+')
p_modify_group.add_argument('-p', '--permissions', nargs='+')
#p_modify_group.set_defaults(func=mg)

p_mg = sp.add_parser('mg', add_help=False, parents=[p_modify_group])
#p_mg.set_defaults(func=mg)

# Subcommand: remove-group
p_remove_group = sp.add_parser('remove-group', add_help=False)
p_add_users_to_group.add_argument('group')
#p_remove_group.set_defaults(func=rg)

p_rg = sp.add_parser('rg', add_help=False, parents=[p_remove_group])
#p_rg.set_defaults(func=rg)

# Subcommand: remove-permissions-from-group
p_remove_permissions_from_group = sp.add_parser('remove-permissions-from-group', add_help=False)
p_remove_permissions_from_group.add_argument('group')
p_remove_permissions_from_group.add_argument('permissions', nargs='+')
#p_remove_permissions_from_group.set_defaults(func=rpg)

p_rpg = sp.add_parser('rpg', add_help=False, parents=[p_remove_permissions_from_group])
#p_rpg.set_defaults(func=rpg)

# Subcommand: remove-users-from-group
p_remove_users_from_group = sp.add_parser('remove-users-from-group', add_help=False)
p_remove_users_from_group.add_argument('group')
p_remove_users_from_group.add_argument('users', nargs='+')
#p_remove_users_from_group.set_defaults(func=rug)

p_rug = sp.add_parser('rug', add_help=False, parents=[p_remove_users_from_group])
#p_rug.set_defaults(func=rug)

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
#                               Miscellaneous Subcommands                             #
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Subcommand: about
p_about = sp.add_parser('about', add_help=False)
#about.set_defaults(func=about)

# Subcommand: version
p_version = sp.add_parser('version', add_help=False)
#version.set_defaults(func=version)

# Subcommand: whoami
p_whoami = sp.add_parser('whoami', add_help=False)
#p_whoami.set_defaults(func=whoami)



args = p.parse_args()
args.func(args)
