#!/usr/bin/env python
import sys
import argparse
from repoman_client.parsers import repoman_cli
from repoman_client.subcommands.help import Help
from repoman_client.subcommands.version import Version
from repoman_client.subcommands.config import MakeConfig
from repoman_client.subcommands.describe import DescribeImage
from repoman_client.subcommands.describe import DescribeUser
from repoman_client.subcommands.describe import DescribeGroup
from repoman_client.subcommands.diagnostic import Whoami
from repoman_client.subcommands.diagnostic import About
from repoman_client.subcommands.create import CreateImage
from repoman_client.subcommands.create import CreateUser
from repoman_client.subcommands.create import CreateGroup
from repoman_client.subcommands.group_membership import AddUserToGroup
from repoman_client.subcommands.group_membership import RemoveUserFromGroup
from repoman_client.subcommands.listing import ListUsers
from repoman_client.subcommands.listing import ListGroups
from repoman_client.subcommands.listing import ListImages
from repoman_client.subcommands.up_down import DownloadImage
from repoman_client.subcommands.up_down import UploadImage
from repoman_client.subcommands.modify import ModifyUser
from repoman_client.subcommands.modify import ModifyGroup
from repoman_client.subcommands.modify import ModifyImage
from repoman_client.subcommands.remove import RemoveUser
from repoman_client.subcommands.remove import RemoveGroup
from repoman_client.subcommands.remove import RemoveImage
from repoman_client.subcommands.save import Save
from repoman_client.subcommands.sharing import ShareImageWithGroups
from repoman_client.subcommands.sharing import ShareImageWithUsers
from repoman_client.subcommands.sharing import UnshareImageWithGroups
from repoman_client.subcommands.sharing import UnshareImageWithUsers

# Add all subcommands here:
repoman_cli.add_subcommand(Help())
repoman_cli.add_subcommand(Version())
repoman_cli.add_subcommand(MakeConfig())
repoman_cli.add_subcommand(DescribeUser())
repoman_cli.add_subcommand(DescribeImage())
repoman_cli.add_subcommand(DescribeGroup())
repoman_cli.add_subcommand(Whoami())
repoman_cli.add_subcommand(About())
repoman_cli.add_subcommand(CreateImage())
repoman_cli.add_subcommand(CreateUser())
repoman_cli.add_subcommand(CreateGroup())
repoman_cli.add_subcommand(AddUserToGroup())
repoman_cli.add_subcommand(RemoveUserFromGroup())
repoman_cli.add_subcommand(ListUsers())
repoman_cli.add_subcommand(ListGroups())
repoman_cli.add_subcommand(ListImages())
repoman_cli.add_subcommand(DownloadImage())
repoman_cli.add_subcommand(UploadImage())
repoman_cli.add_subcommand(ModifyUser())
repoman_cli.add_subcommand(ModifyGroup())
repoman_cli.add_subcommand(ModifyImage())
repoman_cli.add_subcommand(RemoveUser())
repoman_cli.add_subcommand(RemoveGroup())
repoman_cli.add_subcommand(RemoveImage())
repoman_cli.add_subcommand(Save())
repoman_cli.add_subcommand(ShareImageWithGroups())
repoman_cli.add_subcommand(ShareImageWithUsers())
repoman_cli.add_subcommand(UnshareImageWithGroups())
repoman_cli.add_subcommand(UnshareImageWithUsers())




# Check if no arguments were given.  In this case,
# we display a simple help message.
# We do this so that we do not get the default help message,
# which in the case of this application, is too verbal.
if len(sys.argv) == 1:
    print 'repoman: error: too few arguments'
    print 'use "repoman help" for more information'
    sys.exit(1)

# Ask the parser and subparsers to parse the command line arguments.
args = repoman_cli.get_arg_parser().parse_args()

# Run the subcommand function
args.func(args)

# We're done!
sys.exit(0)

# If we decide to go with this OO approach, the rest of this file will have to
# be moved to individual subcommand classes.  See MakeConfig and Help for
# examples.




# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
#                             Group Manipulation Subcommands                          #
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Subcommand: add-permissions-to-group
p_add_permissions_to_group = sp.add_parser('add-permissions-to-group', add_help=False)
p_add_permissions_to_group.add_argument('group')
p_add_permissions_to_group.add_argument('permissions', nargs='+')
#p_add_permissions_to_group.set_defaults(func=apg)

p_apg = sp.add_parser('apg', add_help=False, parents=[p_add_permissions_to_group])
#p_apg.set_defaults(func=apg)








# Subcommand: remove-permissions-from-group
p_remove_permissions_from_group = sp.add_parser('remove-permissions-from-group', add_help=False)
p_remove_permissions_from_group.add_argument('group')
p_remove_permissions_from_group.add_argument('permissions', nargs='+')
#p_remove_permissions_from_group.set_defaults(func=rpg)

p_rpg = sp.add_parser('rpg', add_help=False, parents=[p_remove_permissions_from_group])
#p_rpg.set_defaults(func=rpg)


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
#                               Miscellaneous Subcommands                             #
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #


args = p.parse_args()
args.func(args)
